CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  gameId INT
);

CREATE TABLE games (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE boards (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  gameID INT NOT NULL,
  dimension INT NOT NULL
);

CREATE TABLE tiles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  boardId INT NOT NULL,
  xpos INT NOT NULL,
  ypos INT NOT NULL
);

CREATE TABLE fields (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tileId INT NOT NULL,
  rowId INT NOT NULL,
  artist VARCHAR(255)
);